name: Dinnear
steps:
  - type: task
    key: service-sms-twilio
    instance:
      src: https://github.com/liteflow-services/twilio
      env:
        - TWILIO_ACCOUNT_SID=
        - TWILIO_AUTH_TOKEN=
        - FROM=
    taskKey: sms
    inputs:
      inputs:
      to:
        name: "To"
        description: "The number to recipe SMS"
        type: String
      body:
        name: "Body"
        description: "Text to send SMS"
        type: String
    outputs:
      sid:
        name: "SID"
        description: "Response from Twilio API "
        type: String
  - type: task
    key: erc20-transfer
    instance:
      src: https://github.com/mesg-foundation/service-ethereum-erc20
      env:
        - PROVIDER_ENDPOINT=$(env:PROVIDER_ENDPOINT)
    taskKey: transfer
    inputs:
      privateKey: "$(env:PRIVATE_KEY)"
      contractAddress: "0xd14a3d6b94016e455af5eb7f329bc572ea626c5f"
      gasLimit: 100000
      gasPrice: "10000000000"
      to:
        stepKey: stripe-charge
        key: metadata.address
      value:
        stepKey: stripe-charge
        key: metadata.tokens
  - type: task
    instance:
      src: https://github.com/mesg-foundation/service-js-function
    taskKey: execute
    inputs:
      code: >
        module.exports = (value) => 
          `Hello, Thanks for your payment of $${value.prices / 100}. You will receive ${value.token / 1e18} MESG tokens. See the details of the transaction here https://ropsten.etherscan.io/tx/${value.transaction}`
      inputs:
        prices:
          stepKey: stripe-charge
          key: amount
        token:
          stepKey: stripe-charge
          key: metadata.tokens
        transaction:
          stepKey: erc20-transfer
          key: transactionHash
  - type: task
    instance:
      src: https://github.com/mesg-foundation/service-email-sendgrid
      env:
        - SENDGRID_API_KEY=$(env:SENDGRID_API_KEY)
    taskKey: send
    inputs:
      from: "no-reply@mesg.com"
      to:
        stepKey: stripe-charge
        key: customer
      subject: "Your MESG tokens are coming"
      text:
        key: result
